DocWorks for js-wixcode-sdk - 156 changes detected, but 11 issue detected changes: Service $w.Anchor has changed summary Service $w.Anchor has changed description Service $w.Background message BackgroundOptions member src has changed doc Service $w.Background message BackgroundOptions has changed description Service $w.Box has changed summary Service $w.Box has changed description Service $w.CheckboxGroup has changed summary Service $w.CheckboxGroup has changed description Service $w.CollapsedMixin has changed summary Service $w.CollapsedMixin has changed description Service $w.ContainableMixin has changed summary Service $w.ContainableMixin has changed description Service $w.DatePicker property minDate has changed description Service $w.Document message BackgroundOptions member src has changed doc Service $w.Document message BackgroundOptions has changed description Service $w.Dropdown has changed summary Service $w.Dropdown has changed description Service $w.EffectOptions message ArcEffectOptions member duration has changed doc Service $w.EffectOptions message ArcEffectOptions member delay has changed doc Service $w.EffectOptions message ArcEffectOptions member direction has changed doc Service $w.EffectOptions message ArcEffectOptions has changed description Service $w.EffectOptions message BounceEffectOptions member duration has changed doc Service $w.EffectOptions message BounceEffectOptions member delay has changed doc Service $w.EffectOptions message BounceEffectOptions member direction has changed doc Service $w.EffectOptions message BounceEffectOptions member intensity has changed doc Service $w.EffectOptions message BounceEffectOptions has changed description Service $w.EffectOptions message FadeEffectOptions member duration has changed doc Service $w.EffectOptions message FadeEffectOptions member delay has changed doc Service $w.EffectOptions message FadeEffectOptions has changed description Service $w.EffectOptions message FlipEffectOptions member duration has changed doc Service $w.EffectOptions message FlipEffectOptions member delay has changed doc Service $w.EffectOptions message FlipEffectOptions member direction has changed doc Service $w.EffectOptions message FlipEffectOptions has changed description Service $w.EffectOptions message FloatEffectOptions member duration has changed doc Service $w.EffectOptions message FloatEffectOptions member delay has changed doc Service $w.EffectOptions message FloatEffectOptions member direction has changed doc Service $w.EffectOptions message FloatEffectOptions has changed description Service $w.EffectOptions message FlyEffectOptions member duration has changed doc Service $w.EffectOptions message FlyEffectOptions member delay has changed doc Service $w.EffectOptions message FlyEffectOptions member direction has changed doc Service $w.EffectOptions message FlyEffectOptions has changed description Service $w.EffectOptions message FoldEffectOptions member duration has changed doc Service $w.EffectOptions message FoldEffectOptions member delay has changed doc Service $w.EffectOptions message FoldEffectOptions member direction has changed doc Service $w.EffectOptions message FoldEffectOptions has changed description Service $w.EffectOptions message GlideEffectOptions member duration has changed doc Service $w.EffectOptions message GlideEffectOptions member delay has changed doc Service $w.EffectOptions message GlideEffectOptions member angle has changed doc Service $w.EffectOptions message GlideEffectOptions member distance has changed doc Service $w.EffectOptions message GlideEffectOptions has changed description Service $w.EffectOptions message PuffEffectOptions member duration has changed doc Service $w.EffectOptions message PuffEffectOptions member delay has changed doc Service $w.EffectOptions message PuffEffectOptions has changed description Service $w.EffectOptions message RollEffectOptions member duration has changed doc Service $w.EffectOptions message RollEffectOptions member delay has changed doc Service $w.EffectOptions message RollEffectOptions member direction has changed doc Service $w.EffectOptions message RollEffectOptions has changed description Service $w.EffectOptions message SlideEffectOptions member duration has changed doc Service $w.EffectOptions message SlideEffectOptions member delay has changed doc Service $w.EffectOptions message SlideEffectOptions member direction has changed doc Service $w.EffectOptions message SlideEffectOptions has changed description Service $w.EffectOptions message SpinEffectOptions member duration has changed doc Service $w.EffectOptions message SpinEffectOptions member delay has changed doc Service $w.EffectOptions message SpinEffectOptions member direction has changed doc Service $w.EffectOptions message SpinEffectOptions member cycles has changed doc Service $w.EffectOptions message SpinEffectOptions has changed description Service $w.EffectOptions message TurnEffectOptions member duration has changed doc Service $w.EffectOptions message TurnEffectOptions member delay has changed doc Service $w.EffectOptions message TurnEffectOptions member direction has changed doc Service $w.EffectOptions message TurnEffectOptions has changed description Service $w.EffectOptions message ZoomEffectOptions member duration has changed doc Service $w.EffectOptions message ZoomEffectOptions member delay has changed doc Service $w.EffectOptions message ZoomEffectOptions has changed description Service $w.Event property context has changed summary Service $w.FocusMixin has changed summary Service $w.FocusMixin has changed description Service $w.GoogleMap has a new property center Service $w.GoogleMap has a new property zoom Service $w.GoogleMap has a new property markers Service $w.HiddenMixin has changed summary Service $w.HiddenMixin has changed description Service $w.HiddenMixin operation show has changed description Service $w.HtmlComponent has changed summary Service $w.HtmlComponent has changed description Service $w.HtmlComponent operation onMessage has changed description Service $w.HtmlComponent operation onMessage.examples[1] has changed body Service $w.HtmlComponent operation postMessage.examples[1] has changed body Service $w.HtmlComponentMessageEvent property data has changed type Service $w.Image has changed summary Service $w.Image has changed description Service $w.Image property clickAction.examples[1] has changed body Service $w.Image property fitMode was removed Service $w.MenuContainer has changed summary Service $w.MenuContainer has changed description Service $w.MouseEvent has changed description Service $w.PlayableMixin operation next has changed extra.notes Service $w.PlayableMixin operation onPause has changed extra.notes Service $w.PlayableMixin operation onPlay has changed extra.notes Service $w.PlayableMixin operation pause has changed extra.notes Service $w.PlayableMixin operation play has changed extra.notes Service $w.PlayableMixin operation previous has changed extra.notes Service $w.QuickActionBar has changed summary Service $w.QuickActionBar has changed description Service $w.QuickActionBarItemClickedEvent message QuickActionBarItem member itemType has changed doc Service $w.QuickActionBarItemClickedEvent message QuickActionBarItem has changed description Service $w.RadioButtonGroup has changed summary Service $w.RadioButtonGroup has changed description Service $w.Repeater has changed description Service $w.Repeater property data has changed description Service $w.Slideshow property slides.examples[0] has changed title Service $w.Slideshow operation onChange has changed extra.notes Service $w.Style has changed summary Service $w.Style has changed description Service $w.Table operation onRowSelect has changed description Service $w.Text has changed description Service $w.TextInputMixin operation onInput was removed Service $w.TextInputMixin operation onKeyPress has changed extra.notes Service $w.UploadButton has changed description Service $w.UploadButton.examples[0] has changed body Service $w.UploadButton property value.examples[1] has changed body Service $w.UploadButton operation startUpload.examples[1] has changed body Service $w.UploadButton message UploadedFile member mediaId was removed Service $w.UploadButton message UploadedFile member title was removed Service $w.UploadButton message UploadedFile member width was removed Service $w.UploadButton message UploadedFile member height was removed Service $w.ValidatableMixin has changed summary Service $w.ValidatableMixin has changed description Service $w.ValidatableMixin message ValidityState has changed description Service $w has changed summary Service $w has changed description Service $w operation at has changed description Service $w operation at.examples has 1 examples removed Service $w has a new operation rendered Service npm-modules has changed description Service wix-site operation getSiteStructure has changed description Service wix-site message PrefetchItems member pages has changed optional Service wix-site message PrefetchItems member lightboxes has changed optional Service wix-site message Prefix member type has changed doc Service wix-site message Prefix has changed description Service wix-site message SiteStructure member pages has changed doc Service wix-site message SiteStructure has changed description Service wix-site message StructurePage member name has changed doc Service wix-site message StructurePage has changed description Service wix-storage.Storage has changed summary Service wix-storage.Storage operation setItem has changed extra.notes Service wix-storage has changed summary Service wix-storage has changed description Service wix-window.trackingParameters message CustomEvent has changed description Service wix-window operation copyToClipboard has changed return doc Service wix-window operation copyToClipboard has changed summary Service wix-window operation copyToClipboard has changed description Service wix-window operation copyToClipboard.examples[0] has changed body Service wix-window operation trackEvent has changed description Service $w.HoverBox is new Service $w.VideoBox is new Service wix-events is new
issues:
Property zoom is missing a type annotation (GoogleMap.es6 (235))
Property center is defined two or more times (GoogleMap.es6 (159, 194))
Property zoom is defined two or more times (GoogleMap.es6 (211, 235))
Property markers has mismatching types for get ($w.GoogleMap.markers) and set ($w.GoogleMap) (GoogleMap.es6 (107, 142))
Operation postMessage has an unknown param type * (HtmlComponent.es6 (141))
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (102))
Callback GoogleMapClickEvent is defined two or more times (GoogleMapClickEvent.es6 (4, 10))
Property value has an unknown type * (ValueMixin.es6 (56))
Property value has an unknown type * (ValueMixin.es6 (84))
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 381
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 389